### ISSUE TITLE
Airflow Python Client 2.6.2rc1 "get_tasks" errors out with execution_timeout cannot be None

### ISSUE THREAD

**Issue by potiuk** [apache/airflow-client-python#85] opened 2023-06-18 23:15 UTC
When running https://raw.githubusercontent.com/apache/airflow-client-python/main/dev/test_python_client.py  with 2.6.2rc1 it fails with:

```
Exception when calling DagAPI->get_tasks: Invalid type for variable 'execution_timeout'. Required value type is TimeDelta and passed type was
NoneType at ['received_data']['tasks'][0]['execution_timeout']
```

<img width="1119" alt="Screenshot 2023-06-19 at 01 11 59" src="https://github.com/apache/airflow-client-python/assets/595491/5027d136-ad2b-4ed6-8a8b-30f29dd7bf2f">

The same test run with python-test-client==2.6.1 succeeds

<img width="783" alt="Screenshot 2023-06-19 at 01 14 24" src="https://github.com/apache/airflow-client-python/assets/595491/157b190f-e292-4c89-bae8-d041968f3718">

**Comment by pierrejeambrun** [comment] 2023-06-19 22:39
This is due to `https://github.com/apache/airflow-client-python/pull/82/files#diff-14fa48609e9762537714dd2528f40f8d036ef2e78fe63cd8a23e76fec1eb944f` file `airflow_client/client/model/task.py`.

I don't know why we have such a change.

I tried regenerating the client multiple times but it appears to be the same everytime, :thinking:

Wondering what could cause this diff, still investigating

**Comment by potiuk** [comment] 2023-06-19 23:34
OK. Found it.

It looks like in the past it's been manually patched (maybe @ephraimbuddy remembers more):

https://github.com/apache/airflow-client-python/commit/ddd6fc0545a8066f474c765e1644a5202eebd256

I do not know that much about OpenAPI specs, but I think it's not a bug in generatio, but the issue is that our OpenAPI specification is wrong:

```
        execution_timeout:
          $ref: '#/components/schemas/TimeDelta'
          nullable: true
        retry_delay:
          $ref: '#/components/schemas/TimeDelta'
          nullable: true
```

Should be:

```
        execution_timeout:
          anyOf:
            - type: 'null'   # Note the quotes around 'null'
            - $ref: '#/components/schemas/TimeDelta'
        retry_delay:
          anyOf:
            - type: 'null'   # Note the quotes around 'null'
            - $ref: '#/components/schemas/TimeDelta'
```

This generates this code in models/task.py

```
            'execution_timeout': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'retry_delay': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
```

Which seems pretty expected.

We could again apply manual fix, but maybe more reasonable is to correct the specification.

**Comment by potiuk** [comment] 2023-06-19 23:38
BTW. Seems we already applied the manual patch twice in different vesions of the generated python API and it's neither documented nor nobody remembers we did .

**Comment by ephraimbuddy** [comment] 2023-06-20 06:06
> BTW. Seems we already applied the manual patch twice in different vesions of the generated python API and it's neither documented nor nobody remembers we did (#53 #76)

Yes. @potiuk . Sorry for being late here, I patch it with https://github.com/apache/airflow-client-python/pull/76. 
I will add this to the release guide until we upgrade the client generator to the latest version. I wanted to upgrade it but it seems like it will have some breaking changes.

**Comment by pierrejeambrun** [comment] 2023-06-21 17:43
Thanks guys. (I also agree that the origin of the problem seems like a bad OpenAPI spec).

Closing, now that the issue is identified, and that the process has been updated (Thanks Eprhaim) while we are not upgrading the generator version.

I'm working on rc2.

**Closed by pierrejeambrun** 2023-06-21 17:43 UTC
