### ISSUE TITLE
Not possible to trigger dag run

### ISSUE THREAD

**Issue by piotrlinski** [apache/airflow-client-python#55] opened 2022-12-15 13:27 UTC
According to documentation  the below code should trigger a dug run

`api_response = api_instance.post_dag_run(
dag_id = "dag_name",
 dag_run = DAGRun(..., state=DagState("queued")))`

instead it raises the API error:

`
raise ApiException(http_resp=r)
          airflow_client.client.exceptions.ApiException: (400)
           Reason: BAD REQUEST
           HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 15 Dec 2022 13:18:16 GMT', 'Content-Type': 'application/problem+json', 'Content-Length': '210', 'Connection': 'keep-alive', 'X-Robots-Tag': 'noindex, nofollow', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains'})
           HTTP response body: {
             "detail": "Property is read-only - 'state'",
             "status": 400,
             "title": "Bad Request",
             "type": "https://airflow.apache.org/docs/apache-airflow/2.4.1/stable-rest-api-ref.html#section/Errors/BadRequest"
           }`

**Comment by piotrlinski** [comment] 2022-12-15 15:18
same with postman 

![image](https://user-images.githubusercontent.com/11379223/207898108-7ad206ae-f67f-45a6-8ad8-39669f5ad188.png)

**Comment by potiuk** [comment] 2023-01-02 10:30
I believe this might be caused by old version of the client and some changes since. We are just discussing on making sure the client gets released in https://github.com/apache/airflow/pull/28521 and possibly situation might improve in the future.

**Comment by pierrejeambrun** [comment] 2023-02-24 22:46
Working as expected on latest client version (2.5.1):

```python
    # DagRun
    dag_run_api_instance = dag_run_api.DAGRunApi(api_client)
    try:
        api_response = dag_run_api_instance.post_dag_run(
            "25616-bug", dag_run_api.DAGRun()
        )
        pprint(api_response)
    except airflow_client.client.OpenApiException as e:
        print("Exception when calling DagRunApi->post_dag_run: %s\n" % e)
```
Closing for now, feel free to reopen if needed. :smile:

**Closed by pierrejeambrun** 2023-02-24 22:46 UTC
